"""Bridge to Command: Modern Operations.

The CMO harness (cmo/lua/battlelab/*.lua) does not sample anything itself.
Python draws every run's parameters with the same CRN scheme as the native
engine and writes them into a Lua file that CMO loads with ScenEdit_RunScript.
CMO writes one CSV row per replication with the same `p.`/`m.` column names,
so `ingest()` returns a DataFrame that every analysis function accepts.
"""
from __future__ import annotations

import io
import time
from pathlib import Path

import pandas as pd

from . import __version__
from .params import stable_hash
from .scenario import Scenario

CSV_PREFIX = "BLCSV|"


def _lua_num(x: float) -> str:
    return repr(float(x)) if x == x else "0/0"


def export_design(scenario: Scenario, n: int, seed: int, path: str | Path,
                  params: list[str] | None = None, start: int = 0) -> Path:
    """Write BL_DESIGN = {...} for the CMO harness.

    `params` limits which parameters are exported (default: all). Each run also
    gets its own integer seed for the Lua-side PRNG (unit culling, jitter).
    `start` offsets the run indices, so a batch can be split over several CMO
    sessions (runs start..start+n-1) whose rows append to the same results file.
    """
    names = params or scenario.space.names()
    lines = [
        f"-- generated by battlelab {__version__} on {time.strftime('%Y-%m-%d %H:%M')}",
        f"-- scenario {scenario.id} fingerprint {scenario.fingerprint()} seed {seed}",
        "-- do not edit by hand: regenerate with `battlelab cmo-export`",
        "BL_DESIGN = {",
        f"  scenario = '{scenario.id}',",
        f"  fingerprint = '{scenario.fingerprint()}',",
        f"  seed = {int(seed)},",
        f"  param_names = {{{', '.join(repr(k) for k in names)}}},",
        "  runs = {",
    ]
    for i in range(start, start + n):
        p = scenario.space.sample(seed, i)
        run_seed = (stable_hash(f"{seed}:{i}") % 2147483646) + 1
        kv = ", ".join(f"['{k}']={_lua_num(p[k])}" for k in names)
        lines.append(f"    {{id={i}, seed={run_seed}, p={{{kv}}}}},")
    lines += ["  },", "}", ""]
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines))
    return out


def ingest(path: str | Path) -> pd.DataFrame:
    """Read harness output: a CSV file, or a pasted Lua-console log whose
    result lines start with 'BLCSV|' (the fallback when file I/O is blocked)."""
    text = Path(path).read_text()
    if CSV_PREFIX in text:
        rows = [ln.split(CSV_PREFIX, 1)[1] for ln in text.splitlines() if CSV_PREFIX in ln]
        header = next(r for r in rows if r.startswith("run,"))
        body = [r for r in rows if not r.startswith("run,")]
        text = "\n".join([header] + body)
    df = pd.read_csv(io.StringIO(text))
    df = df.drop_duplicates(subset="run", keep="last").sort_values("run").reset_index(drop=True)
    for c in df.columns:
        if df[c].dtype == object and set(df[c].dropna().unique()) <= {"true", "false"}:
            df[c] = df[c] == "true"
    df.attrs["backend"] = "cmo"
    return df
