--[[
battlelab CMO harness - core
============================
Runs many replications of one scenario inside a single CMO session, using
only functions available in the public (Steam) edition.

How a batch works
  1. On scenario load, BL.start() snapshots every unit (the pristine .scen
     state is the template), deletes them, and waits one minute.
  2. Each replication: re-create units from the template, letting the
     scenario plugin cull/modify/defer them using that run's parameters
     (from BL_DESIGN, generated by `battlelab cmo-export`).
  3. The plugin's on_tick() runs every tick (a RegularTime event calling
     BL.tick()). After cfg.run_hours of game time the plugin's evaluate()
     returns metrics; one CSV row is written.
  4. All units are deleted, the clock runs cfg.settle_hours so weapons in
     flight expire, and the next replication starts. run_hours + settle_hours
     = 48 keeps every replication at the same local time of day.

Nothing here samples parameters: Python does that, so CMO runs and native
battlelab runs share the same draws and the same analysis code.
]]

BL = BL or {}
BL.VERSION = "0.1.0"

BL.cfg = BL.cfg or {}
local function default(k, v) if BL.cfg[k] == nil then BL.cfg[k] = v end end
default("run_hours", 46)             -- game hours per replication
default("settle_hours", 2)           -- empty-world gap between replications
default("output_file", "battlelab_results.csv")
default("end_when_done", false)
default("verbose", true)

-- ---------------------------------------------------------------------------
-- Logging
-- ---------------------------------------------------------------------------
function BL.log(msg)
  if BL.cfg.verbose then print("[battlelab] " .. tostring(msg)) end
end

-- ---------------------------------------------------------------------------
-- PRNG: Park-Miller MINSTD. Exact in both integer and double arithmetic, so
-- results do not depend on which Lua build CMO embeds.
-- ---------------------------------------------------------------------------
local RNG = {}
RNG.__index = RNG
local M31 = 2147483647

function BL.rng(seed)
  local s = math.floor(tonumber(seed) or 1) % M31
  if s <= 0 then s = s + M31 - 1 end
  return setmetatable({s = s}, RNG)
end
function RNG:next() self.s = (self.s * 48271) % M31; return self.s end
function RNG:uniform() return self:next() / M31 end
function RNG:range(lo, hi) return lo + (hi - lo) * self:uniform() end
function RNG:bernoulli(p) return self:uniform() < p end
function RNG:int(lo, hi) return lo + math.floor(self:uniform() * (hi - lo + 1)) end

-- ---------------------------------------------------------------------------
-- Time
-- ---------------------------------------------------------------------------
function BL.now() return ScenEdit_CurrentTime() end   -- UTC seconds

-- ---------------------------------------------------------------------------
-- Output: file if Lua io is permitted, otherwise KeyStore; always echoed to
-- the Lua console with a BLCSV| prefix so a pasted console log is ingestible.
-- ---------------------------------------------------------------------------
BL.out = {mode = nil, path = nil}

local function try_open(path, mode)
  if type(io) ~= "table" or type(io.open) ~= "function" then return nil end
  local ok, f = pcall(io.open, path, mode)
  if ok then return f end
  return nil
end

function BL.output_init(header)
  local folder = rawget(_G, "_scenariofolder_") or ""
  local sep = (folder ~= "" and not folder:match("[/\\]$")) and "/" or ""
  local path = folder .. sep .. BL.cfg.output_file
  local existing = try_open(path, "r")
  local f = try_open(path, "a")
  if f then
    if not existing then f:write(header .. "\n") end
    f:close()
    BL.out.mode, BL.out.path = "file", path
  else
    BL.out.mode = "keystore"
    if ScenEdit_GetKeyValue("bl_results") == "" then
      ScenEdit_SetKeyValue("bl_results", header .. "\n")
    end
  end
  if existing then existing:close() end
  print("BLCSV|" .. header)
  BL.log("output -> " .. BL.out.mode .. (BL.out.path and (" " .. BL.out.path) or ""))
end

function BL.output_row(line)
  print("BLCSV|" .. line)
  if BL.out.mode == "file" then
    local f = try_open(BL.out.path, "a")
    if f then f:write(line .. "\n"); f:close(); return end
    BL.out.mode = "keystore"
  end
  ScenEdit_SetKeyValue("bl_results", ScenEdit_GetKeyValue("bl_results") .. line .. "\n")
end

function BL.dump_results()   -- paste the console output into a file for ingest
  for line in ScenEdit_GetKeyValue("bl_results"):gmatch("[^\n]+") do
    print("BLCSV|" .. line)
  end
end

local function csv_value(v)
  if v == nil then return "" end
  if type(v) == "boolean" then return v and "true" or "false" end
  if type(v) == "number" then
    if v ~= v then return "" end
    return string.format("%.6g", v)
  end
  local s = tostring(v)
  if s:find("[,\"\n]") then s = '"' .. s:gsub('"', '""') .. '"' end
  return s
end
BL.csv_value = csv_value

-- ---------------------------------------------------------------------------
-- Geometry
-- ---------------------------------------------------------------------------
function BL.point_in_poly(lat, lon, poly)
  local inside, j = false, #poly
  for i = 1, #poly do
    local yi, xi, yj, xj = poly[i].lat, poly[i].lon, poly[j].lat, poly[j].lon
    if ((yi > lat) ~= (yj > lat)) and (lon < (xj - xi) * (lat - yi) / (yj - yi) + xi) then
      inside = not inside
    end
    j = i
  end
  return inside
end

function BL.polygon(side, rp_names)
  local pts = ScenEdit_GetReferencePoints({side = side, area = rp_names})
  local poly = {}
  for _, rp in ipairs(pts or {}) do
    poly[#poly + 1] = {lat = tonumber(rp.latitude), lon = tonumber(rp.longitude)}
  end
  if #poly < 3 then error("battlelab: area needs >= 3 reference points, got " .. #poly) end
  return poly
end

function BL.centroid(poly)
  local la, lo = 0, 0
  for _, p in ipairs(poly) do la, lo = la + p.lat, lo + p.lon end
  return la / #poly, lo / #poly
end

-- ---------------------------------------------------------------------------
-- Units
-- ---------------------------------------------------------------------------
function BL.get(guid)
  local ok, u = pcall(ScenEdit_GetUnit, {guid = guid})
  if ok then return u end
  return nil
end

function BL.all_units()
  local out = {}
  for _, s in ipairs(VP_GetSides()) do
    local side = VP_GetSide({side = s.name})
    for _, u in ipairs(side.units or {}) do
      out[#out + 1] = {guid = u.guid, name = u.name, side = s.name}
    end
  end
  return out
end

function BL.starts_with(s, prefix) return s ~= nil and s:sub(1, #prefix) == prefix end

local TYPE_ORDER = {Facility = 1, Ship = 2, Submarine = 3, Aircraft = 4}

function BL.snapshot()
  local tpl, seen, dup = {}, {}, {}
  for _, ref in ipairs(BL.all_units()) do
    local u = BL.get(ref.guid)
    if u and u.type ~= "Weapon" then
      local r = {name = u.name, side = u.side, type = u.type, dbid = tonumber(u.dbid),
                 latitude = tonumber(u.latitude), longitude = tonumber(u.longitude),
                 altitude = tonumber(u.altitude), heading = tonumber(u.heading),
                 proficiency = u.proficiency}
      pcall(function() if u.base and u.base.name and u.base.name ~= u.name then r.base = u.base.name end end)
      pcall(function() if u.loadoutdbid then r.loadoutid = tonumber(u.loadoutdbid) end end)
      pcall(function() if u.mission and u.mission.name then r.mission = u.mission.name end end)
      if seen[r.name] then dup[#dup + 1] = r.name end
      seen[r.name] = true
      tpl[#tpl + 1] = r
    end
  end
  table.sort(tpl, function(a, b)
    local oa, ob = TYPE_ORDER[a.type] or 9, TYPE_ORDER[b.type] or 9
    if oa ~= ob then return oa < ob end
    return a.name < b.name
  end)
  if #dup > 0 then
    BL.log("WARNING duplicate unit names (missions/targets are re-linked by name): "
           .. table.concat(dup, ", "))
  end
  return tpl
end

function BL.spawn(r)
  local d = {type = r.type, name = r.name, side = r.side, dbid = r.dbid,
             latitude = r.latitude, longitude = r.longitude, altitude = r.altitude,
             heading = r.heading, proficiency = r.proficiency}
  if r.base then d.base = r.base end
  if r.loadoutid then d.loadoutid = r.loadoutid end
  local ok, u = pcall(ScenEdit_AddUnit, d)
  if not ok or not u then
    BL.log("spawn failed for " .. tostring(r.name) .. ": " .. tostring(rawget(_G, "_errmsg_") or u))
    return nil
  end
  if r.mission then pcall(ScenEdit_AssignUnitToMission, u.guid, r.mission) end
  return u
end

function BL.teardown()
  local n = 0
  for _, ref in ipairs(BL.all_units()) do
    if pcall(ScenEdit_DeleteUnit, {guid = ref.guid}) then n = n + 1 end
  end
  return n
end

-- ---------------------------------------------------------------------------
-- Replication state machine
-- ---------------------------------------------------------------------------
BL.state = BL.state or {phase = "idle", index = 0}

local function header()
  local cols = {"run", "seed", "cmo_build"}
  for _, m in ipairs(BL.plugin.metric_fields) do cols[#cols + 1] = "m." .. m end
  for _, p in ipairs(BL.design.param_names) do cols[#cols + 1] = "p." .. p end
  return table.concat(cols, ",")
end

function BL.start(plugin, design)
  assert(type(plugin) == "table" and plugin.mutate and plugin.evaluate, "battlelab: bad plugin")
  assert(type(design) == "table" and design.runs and #design.runs > 0, "battlelab: empty design")
  if plugin.scenario and design.scenario ~= plugin.scenario then
    error("battlelab: design is for '" .. tostring(design.scenario) ..
          "' but plugin expects '" .. plugin.scenario .. "'")
  end
  BL.plugin, BL.design = plugin, design
  local resume = tonumber(ScenEdit_GetKeyValue("bl_index")) or 0
  if resume > 0 then
    BL.log("KeyStore says replication " .. resume .. " already ran. Load the pristine .scen "
           .. "to restart, or call BL.reset_progress() first. Batch not started.")
    BL.state.phase = "blocked"
    return false
  end
  BL.template = BL.snapshot()
  BL.log(("template: %d units; design: %d runs (%s)"):format(#BL.template, #design.runs,
         tostring(design.fingerprint)))
  if plugin.on_batch_start then plugin.on_batch_start(BL.template) end
  BL.output_init(header())
  BL.teardown()
  BL.state = {phase = "settle", index = 0, settle_until = BL.now() + 60}
  return true
end

function BL.reset_progress()
  ScenEdit_SetKeyValue("bl_index", "0")
  ScenEdit_SetKeyValue("bl_results", "")
end

local function spawn_record(ctx, rec)
  local u = BL.spawn(rec)
  if u then
    ctx.spawned[rec.name] = u.guid
    if BL.plugin.on_spawned then BL.plugin.on_spawned(ctx, rec, u) end
  end
end

function BL.begin_run()
  local st = BL.state
  st.index = st.index + 1
  local run = BL.design.runs[st.index]
  if not run then
    st.phase = "done"
    BL.log("batch complete: " .. (st.index - 1) .. " replications")
    pcall(ScenEdit_SpecialMessage, "playerside", "battlelab: batch complete")
    if BL.cfg.end_when_done then ScenEdit_EndScenario() end
    return
  end
  local ctx = {run = run, p = run.p, rng = BL.rng(run.seed), t0 = BL.now(), elapsed_h = 0,
               spawned = {}, deferred = {}, state = {}, metrics = {}}
  for _, rec in ipairs(BL.template) do
    local r, defer_h = BL.plugin.mutate(rec, ctx)
    if r and defer_h and defer_h > 0 then
      ctx.deferred[#ctx.deferred + 1] = {at = defer_h, rec = r}
    elseif r then
      spawn_record(ctx, r)
    end
  end
  if BL.plugin.on_run_start then BL.plugin.on_run_start(ctx) end
  st.ctx, st.phase = ctx, "running"
  ScenEdit_SetKeyValue("bl_index", tostring(st.index))
  BL.log(("run %d/%d started (id %s)"):format(st.index, #BL.design.runs, tostring(run.id)))
end

function BL.finish_run()
  local st, ctx = BL.state, BL.state.ctx
  local ok, m = pcall(BL.plugin.evaluate, ctx)
  if not ok then
    BL.log("evaluate failed: " .. tostring(m))
    m = {}
  end
  local cols = {csv_value(ctx.run.id), csv_value(ctx.run.seed),
                csv_value(GetBuildNumber and GetBuildNumber() or "")}
  for _, k in ipairs(BL.plugin.metric_fields) do cols[#cols + 1] = csv_value(m[k]) end
  for _, k in ipairs(BL.design.param_names) do cols[#cols + 1] = csv_value(ctx.p[k]) end
  BL.output_row(table.concat(cols, ","))
  BL.teardown()
  st.phase, st.ctx = "settle", nil
  st.settle_until = BL.now() + BL.cfg.settle_hours * 3600
end

function BL.tick()
  local st = BL.state
  if st.phase == "running" then
    local ctx = st.ctx
    ctx.elapsed_h = (BL.now() - ctx.t0) / 3600
    for i = #ctx.deferred, 1, -1 do
      local d = ctx.deferred[i]
      if ctx.elapsed_h >= d.at then
        table.remove(ctx.deferred, i)
        spawn_record(ctx, d.rec)
      end
    end
    local ok, err = pcall(BL.plugin.on_tick, ctx)
    if not ok then BL.log("on_tick error: " .. tostring(err)) end
    if ctx.elapsed_h >= BL.cfg.run_hours or ctx.done then BL.finish_run() end
  elseif st.phase == "settle" and BL.now() >= st.settle_until then
    BL.begin_run()
  end
end

-- ---------------------------------------------------------------------------
-- Self-test: run from the Lua console before a batch
-- ---------------------------------------------------------------------------
BL.REQUIRED_API = {
  "ScenEdit_AddUnit", "ScenEdit_DeleteUnit", "ScenEdit_GetUnit", "ScenEdit_SetUnit",
  "ScenEdit_SetUnitSide", "ScenEdit_AssignUnitToMission", "ScenEdit_GetMission",
  "ScenEdit_SetMission", "ScenEdit_GetReferencePoints", "ScenEdit_CurrentTime",
  "ScenEdit_SetKeyValue", "ScenEdit_GetKeyValue", "ScenEdit_AddExplosion",
  "VP_GetSides", "VP_GetSide",
}

function BL.selftest(plugin)
  local ok_all = true
  local function check(label, ok, detail)
    print(("[selftest] %-44s %s %s"):format(label, ok and "OK  " or "FAIL", detail or ""))
    ok_all = ok_all and ok
  end
  for _, fn in ipairs(BL.REQUIRED_API) do check("API " .. fn, type(rawget(_G, fn)) == "function") end
  local folder = rawget(_G, "_scenariofolder_") or ""
  local f = try_open(folder .. "/battlelab_selftest.tmp", "w")
  if f then f:write("ok"); f:close() end
  check("file output (else KeyStore fallback)", true, f and "file" or "keystore")
  ScenEdit_SetKeyValue("bl_selftest", "42")
  check("KeyStore round trip", ScenEdit_GetKeyValue("bl_selftest") == "42")
  local units = BL.all_units()
  check("units visible", #units > 0, "(" .. #units .. ")")
  local tpl = BL.snapshot()
  local with_dbid = 0
  for _, r in ipairs(tpl) do if r.dbid then with_dbid = with_dbid + 1 end end
  check("snapshot has DBIDs", with_dbid == #tpl, ("(%d/%d)"):format(with_dbid, #tpl))
  if plugin and plugin.selftest then
    for _, c in ipairs(plugin.selftest(tpl)) do check(c[1], c[2], c[3]) end
  end
  print("[selftest] " .. (ok_all and "ALL CHECKS PASSED" or "SOME CHECKS FAILED - see above"))
  return ok_all
end

return BL
